export const seedProducts = [
  { code: '6022', item: 'MARBORO GLOD', stockOnHand: 0, minStockLevel: 10 },
  { code: '6023', item: 'CAMEL BLUE', stockOnHand: -2, minStockLevel: 10 },
  { code: '6024', item: 'SUN CREAM', stockOnHand: 50, minStockLevel: 10 },
  { code: '6025', item: 'SUN CREAM 5 FREE 1', stockOnHand: 0, minStockLevel: 10 },
  { code: '6001', item: 'RPM REFILL BLUE BOTTLE 750 ML.', stockOnHand: 70, minStockLevel: 10 },
  { code: '6002', item: 'RPM REFILL BLUE BOTTLE 750 ML. - STAFF', stockOnHand: 0, minStockLevel: 10 },
  { code: '6003', item: 'RPM WITHE MUG', stockOnHand: 0, minStockLevel: 10 },
  { code: '6004', item: 'RPM WITH MUG - STAFF', stockOnHand: 0, minStockLevel: 10 },
  { code: '6005', item: 'RPM CLOTH BAG', stockOnHand: 50, minStockLevel: 10 },
  { code: '6006', item: 'RPM CLOTH BAG - STAFF', stockOnHand: 0, minStockLevel: 10 },
  { code: '6007', item: 'RPM DRY BAG 10 L.', stockOnHand: 69, minStockLevel: 10 },
  { code: '6008', item: 'RPM DRY BAG 10 L. - STAFF', stockOnHand: 0, minStockLevel: 10 },
  { code: '6009', item: 'RPM DRY BAG 5 L.', stockOnHand: 75, minStockLevel: 10 },
  { code: '6010', item: 'RPM DRY BAG 5 L. - STAFF', stockOnHand: 0, minStockLevel: 10 },
  { code: '6011', item: 'RPM HADHELD FAN', stockOnHand: 35, minStockLevel: 10 },
  { code: '6012', item: 'RPM HADHELD FAN - STAFF', stockOnHand: 0, minStockLevel: 10 },
  { code: '6013', item: 'RPM BEER COVER', stockOnHand: 105, minStockLevel: 10 },
  { code: '6014', item: 'RPM BEER COVER - STAFF', stockOnHand: 0, minStockLevel: 10 },
  { code: '6015', item: 'RPM BUCKET HAT', stockOnHand: 75, minStockLevel: 10 },
  { code: '6016', item: 'RPM BUCKET HAT - STAFF', stockOnHand: 0, minStockLevel: 10 },
  { code: '6017', item: 'RPM WATERPROFF PHONE CASE - 199', stockOnHand: 111, minStockLevel: 10 },
  { code: '6018', item: '2 PHONE CASE = 350.-', stockOnHand: 0, minStockLevel: 10 },
  { code: '6019', item: '3 PHONE CASE = 500.-', stockOnHand: 0, minStockLevel: 10 },
  { code: '6018_2', item: 'RPM POLO WHITE SHIRT', stockOnHand: 6, minStockLevel: 10 },
  { code: '6019_2', item: 'RPM POLO WHITE SHIRT - STAFF', stockOnHand: 0, minStockLevel: 10 },
  { code: '6120', item: 'RPM UMBRELLA', stockOnHand: 22, minStockLevel: 10 },
  { code: '6121', item: 'RPM UMBRELLA - STAFF', stockOnHand: 0, minStockLevel: 10 }
];
